name: Deploy the backend

on:
  push:
    braanches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with :
          usename: ${{secrets.DOCKERHUB_USERNAME}}
          passworrd: ${{secrets.DOCKERHUB_TOKEN}}

      - name : Build and push
        uses : docker/build-push-action@v4
        with:
          context : .
          file : ./docker/Dockerfile.be
          push : true
          tags : ${{secrets.DOCKERHUB_USERNAME}}/docker-tut-backend:${{github.sha}}